
spring:
  application.name: spring_demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      test-on-borrow: true
      validationQuery: SELECT 1
      test-while-idle: true
      timeBetweenEvictionRunsMillis: 60000
  redis:
    host: localhost
    port: 6379
    password: ""
  jpa:
    show-sql: false
    hibernate: # https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html/ch03.html#configuration-optional
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
      ddl-auto: validate

  flyway.enabled: false  # prevent migrations on application server startup

  #disabled security for actuator
  management.security.enabled: false

uken:
  hello_response: 'Hello Uken!'
  metrics:
    prefix: spring_demo
    tags:
      - key: env
        value: staging
      - key: app
        value: spring_demo

# everything above is default configuration for every profile

---

# this overrides the defaults when running with the test profile

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:hoth:MODE=MySQL # use the in memory h2 DB instead of spinning up MySQL
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway.enabled: false
