spring.application.name: spring_demo

---

spring:
  profiles: dev

uken:
  hello_response: Default
  dogstatsd:
    prefix: mattest
    host: localhost
    port: 8125
    tags:
      - 'env:dev'
      - 'key:value'

#disabled security for actuator
management.security.enabled: false
