
spring:
  application.name: spring_demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
    username: root
    password: ""
    test-while-idle: true
    validationQuery: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
#  redis:
#    host: localhost
#    port: 6382
#    password: ""
  jpa:
    show-sql: false
    hibernate: # https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html/ch03.html#configuration-optional
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
      ddl-auto: validate

flyway.enabled: false  # prevent migrations on application server startup

uken:
  hello_response: 'Hello Uken!'
  dogstatsd:
    prefix: demo
    host: localhost
    port: 8125
    tags:
      - 'env:dev'
      - 'key:value'

#disabled security for actuator
management.security.enabled: false
